### ISSUE TITLE
QR Code Template Enhancement

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#114]
Editable Font size, font color and font type for each section

**Comment by lurhays** [comment]
Added collapsible floating panel for user to edit title, description and footer. Collapsed at page load.

Editable pieces includes font size, font color (using picker or hex code manual entry), font type and the text itself.

Fonts are fixed to:
system-ui
Times New Roman
Georgia
Garamond
Arial
Verdana
Helvetica
Courier New
Lucida Console
Monaco
Brush Script MT
Lucida Handwriting
Copperplate
Papyrus

Clicking the template would reset the QR code template, and user can proceed with text edit from there.

Snapshots below:
<img width="746" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/76f63bca-c525-473a-8736-2c92399d53df">

<img width="741" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/5ae8a92c-a2db-494a-b24f-21cd147cdc99">

**Comment by lurhays** [comment]
Refer pull request #116.

**Comment by rohaizanr** [comment]
terima kasih
