### ISSUE TITLE
Public-web: Display nama masjid from tetapan-public-api

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#115]
<img width="457" alt="Screenshot 2024-02-21 at 11 31 52 PM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/bb0fb656-b8de-43e3-881d-70abb6042aef">

<img width="232" alt="Screenshot 2024-02-21 at 11 32 03 PM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/4a00716c-58d3-40c5-adea-23ef20e12e9d">

**Comment by naimhasim** [comment]
makluman isu CORS dari tetapan-public-api di public-web.
 
```Access to XMLHttpRequest at 'http://localhost:8085/tetapan/NAMA_MASJID' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by rohaizanr** [comment]
tetapan-public-api belum siap, issue --> https://github.com/Dev4w4n/e-masjid.my/issues/111

http://localhost:8085/tetapan <--- ini untuk secure dashboard API

saya akan explain lebih dalam dev meetup esok

https://discord.gg/xdP2fFZy?event=1215995851592302663

**Comment by naimhasim** [comment]
baik, insyaAllah.

**Comment by rohaizanr** [comment]
http://localhost:8086/tetapan/NAMA_MASJID

**Comment by rohaizanr** [comment]
@naimhasim boleh continue

**Comment by rohaizanr** [comment]
terima kasih @naimhasim
