### ISSUE TITLE
Handle Mobile View for Download QR Cadangan

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#117]

**Comment by lurhays** [comment]
Changes made to QR template and text editor panel for mobile view.

<img width="349" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/59ecc161-7604-427b-8aa5-e94c3bab0a52">

**Comment by lurhays** [comment]
Please review PR #140

**Comment by rohaizanr** [comment]
perfect!
