### ISSUE TITLE
Dashboard > Tabung enhancement (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#133]
Requirement: ReactJs only, (API dan DB supported)

Butiran feature:

Tabung > Tetapan: (ui#/tabung/tetapan)
- Tambah true/false checkbox dan boleh save untuk setiap Tabung column "is_cents"

Tabung > Daftar: (ui#/tabung/daftar)
- Jika "is_cent" is true, display entry 1c, 5c, 10c, 20c & 50c

Tabung > Cetak: (ui#/tabung/cetak)
- Jika "is_cent" is true, display print area 1c, 5c, 10c, 20c & 50c

**Comment by lurhays** [comment]
Feature implemented. 

Tabung > Tetapan: (ui#/tabung/tetapan)
Tambah true/false checkbox dan boleh save untuk setiap Tabung column "is_cents"
<img width="569" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/d5c1259e-48bd-4c47-8db3-ef2c4582c50f">

Tabung > Daftar: (ui#/tabung/daftar)
Jika "is_cent" is true, display entry 1c, 5c, 10c, 20c & 50c
<img width="738" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/cd9f5af7-9b7b-4434-8ee9-517f166088c4">

Tabung > Cetak: (ui#/tabung/cetak)
Jika "is_cent" is true, display print area 1c, 5c, 10c, 20c & 50c
<img width="607" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/311bc85c-1952-44c6-86a2-b40941c22349">

**Comment by lurhays** [comment]
PR #144.

**Comment by rohaizanr** [comment]
terima kasih
