### ISSUE TITLE
ENHANCEMENT : Tabung > Cetak - Edit (ReactJS + Go) 

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#142]
Boleh edit tarikh dan kiraan

Expected delivery time: 2 minggu

**Comment by nazhansukri11** [comment]
Boleh assign ke saya, saya cuba

**Comment by nazhansukri11** [comment]
Assign to me

**Comment by rohaizanr** [comment]
@adamjanin - API
@nazhansukri11 -UI

boleh try guna discord untuk collab.
ping saya kalau ada masalah > 10:30PM anyday

terima kasih

**Comment by adamjanin** [comment]
@rohaizanr , kalau aku nak tambah column "updated_date", macam mana process dia? kene buat migration script ke?

**Comment by rohaizanr** [comment]
> @adamjanin kalau aku nak tambah column "updated_date", macam mana process dia? kene buat migration script ke?

1. append line alter table di postgres/tabung.sql
2. delete current local container
3. sh run-dev.sh

**Comment by adamjanin** [comment]
@rohaizanr , haha rasa macam big change lak bila tambah column baru. aku ubah yg created_date aje lah
PR for api change : https://github.com/Dev4w4n/e-masjid.my/pull/164

**Comment by rohaizanr** [comment]
PR merged.

@nazhansukri11 mohon re-sync fork

curl --location --request PUT 'http://localhost:8082/kutipan/:id' \ --header 'Content-Type: application/json' \ --data '{ "createDate": 1711293410193, "total1c": 0, "total5c": 0, "total10c": 0, "total20c": 0, "total50c": 0, "total1d": 0, "total5d": 0, "total10d": 0, "total20d": 10, "total50d": 12, "total100d": 0 }'

**Comment by nazhansukri11** [comment]
Tertanya-tanya adakah masalah ini disebabkan code saya atau disebabkan benda lain.

![image](https://github.com/Dev4w4n/e-masjid.my/assets/70995671/1f157292-3eb9-42d7-a6d5-e59b32acbe53)

**Comment by rohaizanr** [comment]
@nazhansukri11  jap saya fix.

**Comment by rohaizanr** [comment]
edit file ./api/tabung-api/main.go

line 41

config.AllowMethods = []string{"GET", "POST", "DELETE", "PUT"}

lepas tu run-dev.sh balik

**Comment by rohaizanr** [comment]
terima kasih @adamjanin @nazhansukri11
