### ISSUE TITLE
Tukar link Bahan Rujukan (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#150]
<img width="402" alt="Screenshot 2024-03-20 at 8 13 34 PM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/2a40f319-7615-49db-9133-325b9923f3d0">

tukar ke https://docs-e-masjid-my.pages.dev/

Web view and mobile view

**Comment by m-amirazmi** [comment]
Assign this to me

**Comment by rohaizanr** [comment]
terima kasih
