### ISSUE TITLE
ENHANCEMENT: Cadangan > Senarai - Pagination (ReactJS + Go)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#151]
<img width="1293" alt="Screenshot 2024-03-20 at 8 16 15 PM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/9d6fc2db-1fa8-4fce-9f5a-2a025560905b">

Perlu pagination

**Comment by faizshukri** [comment]
Boleh assign ni kt sy.

Btw pagination perlu di semua tab atau di tab Selesai sahaja?

**Comment by rohaizanr** [comment]
@faizshukri assigned.

semua tab. terima kasih

**Comment by faizshukri** [comment]
https://github.com/Dev4w4n/e-masjid.my/assets/1219518/ffddd165-0be2-4e8b-becd-e03bff227edf

Okay ke buat remote pagination macam ni? (rows per page tu utk testing, yg betul saya follow mcm di carian khairat, 25,50,100,200)

> Cadangan > Cetak - Pagination

Apa maksud **Cetak** - Pagination?

**Comment by rohaizanr** [comment]
nice work @faizshukri 

sorry, sepatutnya Cadangan > Senarai (navigation menu tepi)

![Screenshot 2024-03-22 at 12 26 43 AM](https://github.com/Dev4w4n/e-masjid.my/assets/11247162/9be96c31-2ef6-4992-9ebe-625f6685199b)
