### ISSUE TITLE
Mobile view enhancement: Public-web (ReactJS) 

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#155]
Jadikan "Log Masuk AJK" header link di Mobile View tanpa perlu klik menu button.

![Screenshot 2024-03-21 at 11 12 04 PM](https://github.com/Dev4w4n/e-masjid.my/assets/11247162/86aef343-6f69-4aab-83a2-d2ad28ee8090)

**Comment by m-amirazmi** [comment]
Assign this to me

**Comment by m-amirazmi** [comment]
The fix has been done
[#158](https://github.com/Dev4w4n/e-masjid.my/pull/158)

Thank you

**Comment by rohaizanr** [comment]
terima kasih
