### ISSUE TITLE
UI bug: Public-web: Mobile view (REACTJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#159]
Masalahnya di mobile view, boleh skrol ke kiri dan kanan, sepatutnya boleh skrol ke atas dan bawah sahaja.

Ini membuatkan effect scrolling tak kemas.

<img width="346" alt="Screenshot 2024-03-24 at 12 12 18 AM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/f0ebd813-a159-4885-9b4c-1e9b32c27126">

**Comment by waziaq** [comment]
@rohaizanr boleh assign kepada saya, terima kasih

**Comment by rohaizanr** [comment]
terim kasih @waziaq

**Comment by rohaizanr** [comment]
@waziaq 

Expected delivery 5 hari cukup ?

**Comment by waziaq** [comment]
> @waziaq
> 
> Expected delivery 5 hari cukup ?

Maaf sy dah update, malam-malam sy akan update

**Comment by rohaizanr** [comment]
terima kasih @waziaq , jap saya tengok

**Comment by rohaizanr** [comment]
id discord apa @waziaq ?
