### ISSUE TITLE
API Documentation untuk E-Masjid.My - Go

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#163]
Expected result:

1. Browser-based editor where you can write and edit API documentation and OpenAPI specification
2. Dockerfile - container to host api-docs, so that it can be deployed to api-docs.e-masjid.my

Expected delivery time: 3 weeks

Comment: "Assign this to me", if you wish to pick this up

**Comment by adamjanin** [comment]
This will take some time to complete due to a lot of code refactoring that needs to be done

**Comment by adamjanin** [comment]
@rohaizanr  macam ni okay kan? 

![image](https://github.com/Dev4w4n/e-masjid.my/assets/22977046/d560033b-065d-4e3e-80f0-622dc64839a2)
![image](https://github.com/Dev4w4n/e-masjid.my/assets/22977046/efa7bedf-4d8a-4961-a0e6-53754a80111e)

**Comment by rohaizanr** [comment]
Nice

**Comment by adamjanin** [comment]
PR: https://github.com/Dev4w4n/e-masjid.my/pull/221
