### ISSUE TITLE
Restructuring Dashboard ReactJS codes

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#165]
***Expected result:***
1. Change Create React App (CRA) to React Vite
2. Add Typescript support
3. Feature slice folder structure
4. Add tanstack-query for API fetching
5. Change redux to redux-toolkit or other global state (need discussion)
6. Use redux-toolkit or change to other solution like zustand.

***Expected delivery time:***
2 week

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by hisyamnasir** [comment]
assign to me

**Comment by hisyamnasir** [comment]
Expected result:

1. Change Create React App (CRA) to React Vite
2. Add Typescript support
3. Feature slice folder structure
4. Add `tanstack-query` for API fetching
5. Change `redux` to `redux-toolkit` or other global state (need discussion)

   - Use `redux-toolkit` or change to other solution like `zustand`.
   
   
p/s: Will edit and add more later

**Comment by waziaq** [comment]
> Expected result:
> 
> 1. Change Create React App (CRA) to React Vite
> 2. Add Typescript support
> 3. Feature slice folder structure
> 4. Add `tanstack-query` for API fetching
> 5. Change `redux` to `redux-toolkit` or other global state (need discussion)
>    
>    * Use `redux-toolkit` or change to other solution like `zustand`.
> 
> p/s: Will edit and add more later

Vote for zustand

**Comment by rohaizanr** [comment]
TODO: create a new branch and split tasks

**Comment by rohaizanr** [comment]
Terima kasih
