### ISSUE TITLE
PUBLIC-WEB annoying console error

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#168]
1. Open https://demo.e-masjid.my/

2. Tengok console log

![Screenshot 2024-03-26 at 11 19 45 PM](https://github.com/Dev4w4n/e-masjid.my/assets/11247162/e72a2603-a849-4797-b58c-6ada784db761)

**Comment by rohaizanr** [comment]
@m-amirazmi tolong tengok jap benda apa ni

**Comment by m-amirazmi** [comment]
macam mana nk recreate issue ni ye sbb sy cuba kt https://demo.e-masjid.my/ mcm x ada apa2 pun console error. maybe sbb issue plugin or browser tu sendiri?

**Comment by waziaq** [comment]
Saya rasa benda yg sama, sbb sy punya local tiada error tersebut

**Comment by Dev4w4n** [comment]
> macam mana nk recreate issue ni ye sbb sy cuba kt https://demo.e-masjid.my/ mcm x ada apa2 pun console error. maybe sbb issue plugin or browser tu sendiri?

hmmm ... saya sorang je ke ?

**Comment by Dev4w4n** [comment]
> macam mana nk recreate issue ni ye sbb sy cuba kt https://demo.e-masjid.my/ mcm x ada apa2 pun console error. maybe sbb issue plugin or browser tu sendiri?

<img width="379" alt="Screenshot 2024-03-27 at 1 05 17 AM" src="https://github.com/Dev4w4n/e-masjid.my/assets/153977315/45df2eb7-3572-4bd9-9395-129919b2a78f">

**Comment by rohaizanr** [comment]
boleh ignore .. kalau orang lain tak complain

**Comment by rohaizanr** [comment]
others can't reproduce
