### ISSUE TITLE
Script to create sample data for local dev

### ISSUE THREAD

**Issue by Dev4w4n** [Dev4w4n/e-masjid.my#169]
***Expected result:***
1. Once all container is up, run the script and populate dummy data

***Expected delivery time:***
2 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by faizshukri** [comment]
Assign to me

**Comment by rohaizanr** [comment]
@faizshukri rasanya tak perlu complicated script sangat.

Just append *.sql dalam ./postgres

**Comment by faizshukri** [comment]
Okay, boleh.

`./postgres` ni untuk dev purpose saja ka? Masa nak setup masjid baru, tak pakai ye image ni?

**Comment by rohaizanr** [comment]
> Okay, boleh.
> 
> 
> 
> `./postgres` ni untuk dev purpose saja ka? Masa nak setup masjid baru, tak pakai ye image ni?

Oppss you're right.
Hmmmm.
Kena buat separate dummy.sql
