### ISSUE TITLE
Refactor Khairat Module Table Name (SQL + GO)

### ISSUE THREAD

**Issue by lurhays** [Dev4w4n/e-masjid.my#172]
***Expected result:***
1. Change members table name to khairat_members.
2. Change members_tags table name to khairat_members_tags.
3. Change tags table name to khairat_tags.
4. Change dependents table name to khairat_dependents
5. Refactor khairat-api to using the new table names.
6. Script to migrate existing data to new table names.

***Expected delivery time:***
2 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by rohaizanr** [comment]
append alter statement dalam table.sql

contoh 
--- changes in v1.10-beta.10 (current release)
alter table bla bla bla;

**Comment by adamjanin** [comment]
PR: https://github.com/Dev4w4n/e-masjid.my/pull/233

**Comment by rohaizanr** [comment]
terima kasih
