### ISSUE TITLE
PUBLIC-Web Waktu Solat bug (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#178]
Bila https://api.waktusolat.app/v2/solat/ response error , public-web akan down.

Perlu ada try catch untuk disable Waktu solat jika 3rd party API down.

Estimate : 3 days

**Comment by Dev4w4n** [comment]
@dr-msr still valid tak bug ni? kalau tak kita boleh close

**Comment by dr-msr** [comment]
Should be okay dah kot sebab dah letak validation tu. Kalau jadi lagi kita open balik hehe
