### ISSUE TITLE
CADANGAN-API delete (GO)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#179]
***Expected result:***
1. Endpoint baru untuk delete cadangan by id
2. Nama endpoint  DELETE /cadangan/{id}

***Expected delivery time:***
3 days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by QuantMis** [comment]
Assign this to me

**Comment by rohaizanr** [comment]
terima kasih @QuantMis

**Comment by rohaizanr** [comment]
terima kasih
