### ISSUE TITLE
E-Masjid.My API Postman Collections

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#185]
***Expected result:***
1. Postman collections for E-Masjid.my API
2. Save collection somewhere (cloud or github)

***Expected delivery time:***
1 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by rohaizanr** [comment]
boleh try sedut dari sini

https://api-docs.e-masjid.my/

**Comment by iamariffikri** [comment]
Assign this to me

**Comment by iamariffikri** [comment]
Postman collection v0.1

Only completed Khairat API. Pending rest of the API. Will continue.

[E-Masjid.postman_collection_v0_1.json](https://github.com/user-attachments/files/15747242/E-Masjid.postman_collection_v0_1.json)

**Comment by rohaizanr** [comment]
ok @iamariffikri

**Comment by iamariffikri** [comment]
Postman collection v1

[E-Masjid.postman_collection_v1.json](https://github.com/user-attachments/files/15909258/E-Masjid.postman_collection_v1.json)

**Comment by rohaizanr** [comment]
terima kasih

**Comment by rohaizanr** [comment]
https://github.com/Dev4w4n/e-masjid.my/wiki/E%E2%80%90Masjid-API-Postman-Collections
