### ISSUE TITLE
Prepare tetapan_types data (SQL)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#191]
***Expected result:***
1. Prepare ./postgres/tetapan_types.sql
2. Scrape dropdown data from MasjidPro  

> 1. Negeri
> 2. Pekerjaan
> 3. Status perkahwinan
> 4. Jantina
> 5. Bangsa
> 6. Pendapatan Isi Rumah
> 7. Jenis OKU
> 8. Jenis Penyakit

Go to MasjidPro
1. https://www.masjidpro.com/Masjid/daftar_online/pendaftaran.php?redirect=&id_masjid=3744
2. Select MyKad
3. Key "111"
4. Click Semak
5. Scrape the dropdown data

***Expected delivery time:***
1 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by QuantMis** [comment]
Assign to me.

**Comment by faizshukri** [comment]
Ni data asas untuk semua masjid kan? Kenapa tak letak dlm `tetapan.sql` saja @rohaizanr ?

**Comment by rohaizanr** [comment]
@faizshukri your concern make sense jugak. Yg ni bukan dummy data.

@QuantMis please buat dalam file nama tetapan-types.sql

Terima kasih

**Comment by QuantMis** [comment]
@rohaizanr ok baik

**Comment by rohaizanr** [comment]
terima kasih
