### ISSUE TITLE
ALTER person table (SQL)

### ISSUE THREAD

**Issue by lurhays** [Dev4w4n/e-masjid.my#192]
***Expected result:***
1. Add jantina_types_id, tarikh lahir, email address
2. jantina_types_id refers to tetapan_types table

***Expected delivery time:***
3 days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by rohaizanr** [comment]
append alter statement dalam table.sql

contoh 
--- changes in v1.10-beta.10 (current release)
alter table bla bla bla;

**Comment by rohaizanr** [comment]
terim kasih
