### ISSUE TITLE
Public-web - Add Page & Footer Link - Terms & Privacy (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#193]
***Expected result:***
1. Tambah link Dasar Privasi (Footer) https://cdn.e-masjid.my/volume/DASAR.PRIVASI.pdf
2. Tambah link Terma Perkhidmatan (Footer) https://cdn.e-masjid.my/volume/TERMA.PERKHIDMATAN.pdf

***Expected delivery time:***
3 Days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by naimhasim** [comment]
Assign this to me

**Comment by naimhasim** [comment]
<img width="1500" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/53414003/32d829a4-b415-4005-ad4a-57d107727dbd">

tambah link di bahagian Tentang Masjid atau Copyright mcm Dashboard?

**Comment by rohaizanr** [comment]
@naimhasim  copyright mcm dashboard
