### ISSUE TITLE
Dashboard - Add Page & Footer Link - Terms & Privacy (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#194]
***Expected result:***
1. Tambah link Dasar Privasi (Footer) https://cdn.e-masjid.my/volume/DASAR.PRIVASI.pdf
2. Tambah link Terma Perkhidmatan (Footer) https://cdn.e-masjid.my/volume/TERMA.PERKHIDMATAN.pdf

***Expected delivery time:***
3 Days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by nazhansukri11** [comment]
Assign this to me

**Comment by nazhansukri11** [comment]
Dokumen ini lebih baik dalam pdf ke atau memang word sahaja? 

Once user click, automatic file akan download
![image](https://github.com/Dev4w4n/e-masjid.my/assets/70995671/d5ac457f-5b79-4b67-a434-c6041f29ce48)

**Comment by rohaizanr** [comment]
Good question @nazhansukri11 

Baik saya letak dalam cdn.e-masjid.my. Senang nak manage in future.

Bila orang click, PDF akan buka di new browser tab. Boleh macam tu ?

**Comment by rohaizanr** [comment]
re-assigning

Comment: "Assign this to me", if you wish to pick this up
