### ISSUE TITLE
Dashboard > Tabung

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#198]
**Describe the bug**
Di page Tabung > Daftar , tukar label Tarikh ke Tarikh kutipan

Di page Tabung > Cetak, setelah edit tukar label Tarikh ke Tarikh kutipan

Di page Tabung > Cetak, setelah edit preload Tarikh ke Tarikh kutipan

Expected delivery time:
3 Days

**Comment by nazhansukri11** [comment]
Assign this to me

**Comment by rohaizanr** [comment]
terima kasih
