### ISSUE TITLE
TABUNG-API delete (GO) 

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#201]
***Expected result:***
1. Endpoint baru untuk delete kutipan by id
2. Nama endpoint DELETE /kutipan/{id}

***Expected delivery time:***
3 days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by adamjanin** [comment]
PR : https://github.com/Dev4w4n/e-masjid.my/pull/218
