### ISSUE TITLE
ENHANCEMENT : Tabung > Cetak - Delete (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#219]
***Expected result:***
1. Icon delete di Tabung > Cetak
2. Guna endpoint ```curl --location --request DELETE 'localhost:8082/kutipan/9'```

***Expected delivery time:***
3 days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by adamjanin** [comment]
PR: https://github.com/Dev4w4n/e-masjid.my/pull/220
