### ISSUE TITLE
ENHANCEMENT : Cadangan > Senarai - Delete (ReactJS)

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#229]
***Expected result:***
1. Tambah button "Buang" di model popup cadangan
2. [API Docs Cadangan Delete](https://api-docs.e-masjid.my/?urls.primaryName=Cadangan-API#/cadangan/delete_cadangan__id_)

***Expected delivery time:***
3 days

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by adamjanin** [comment]
https://github.com/Dev4w4n/e-masjid.my/pull/270

**Comment by rohaizanr** [comment]
terima kasih
