### ISSUE TITLE
Tetapan Masjid

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#24]
Dashboard + API

Settings masjid:
1. nama masjid
2. alamat
3. no telefon

Tiga ni dulu la.

**Comment by erosanwar** [comment]
![emasjid-tetapan](https://github.com/Dev4w4n/e-masjid.my/assets/6248592/cb210249-eaeb-4df9-ae57-2e5b06bbb08b)

Backend in progress 😉
