### ISSUE TITLE
[PUBLIC-WEB] Update all libraries to latest

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#265]
***Expected result:***
1. PUBLIC_WEB project updated with latest library.

***Expected delivery time:***
1 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by AimanFariz** [comment]
https://github.com/Dev4w4n/e-masjid.my/pull/269

ran npm update, can still run Docker container and open public-web on Edge. Assuming nothing's broken
