### ISSUE TITLE
[API] Update all libraries to latest

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#267]
***Expected result:***
1. ALL API projects updated with latest library.

***Expected delivery time:***
1 weeks

***Comment: "Assign this to me", if you wish to pick this up***

**Comment by adamjanin** [comment]
@rohaizanr untuk golang saja kan?

**Comment by rohaizanr** [comment]
> @rohaizanr untuk golang saja kan?

Ya

**Comment by adamjanin** [comment]
https://github.com/Dev4w4n/e-masjid.my/pull/271
