### ISSUE TITLE
Perlu tambah validation supaya user tak boleh enter huruf di IC No & No telefon (Demo)

### ISSUE THREAD

**Issue by araf-dev** [Dev4w4n/e-masjid.my#49]
![image](https://github.com/Dev4w4n/e-masjid.my/assets/155940066/fbfebf42-f8a0-4ce8-bd12-68eb84efb26d)

![image](https://github.com/Dev4w4n/e-masjid.my/assets/155940066/32f49c8d-9bcb-4fdf-afe9-af17f7c3115a)

**Comment by rohaizanr** [comment]
Mohon sahkan https://github.com/Dev4w4n/e-masjid.my/pull/50

**Comment by amd-arafat** [comment]
> Mohon pengesahan https://demo.e-masjid.my/

Issue fixed. Terima kasih
