### ISSUE TITLE
README: Tambah maklumat Keperluan Sistem Minima

### ISSUE THREAD

**Issue by wanahmadzainie** [Dev4w4n/e-masjid.my#53]
Cadangan untuk memasukkan Keperluan Sistem Minima (Minimum System Requirement) untuk pembina (developer) and pengguna (end user).

Dicadangkan senarai seperti berikut,
1. sistem operasi dan versi minima,
2. pemproses dan jumlah teras minima,
3. memori minima,
4. storan minima,

**Comment by rohaizanr** [comment]
Cadangan yang baik. 
Basically, untuk Dev environment kena install Docker.

Boleh ambil min req dari sini, dan add masuk README di bahagian Prerequisite. 
https://docs.docker.com/desktop/install/windows-install/
https://docs.docker.com/desktop/install/linux-install/

Boleh cuba.

**Comment by rohaizanr** [comment]
Boleh abaikan enduser sebab masih lagi Beta

**Comment by ridhwn** [comment]
Test Comment

**Comment by rohaizanr** [comment]
@wanahmadzainie tolong komen https://github.com/Dev4w4n/e-masjid.my/pull/83
