### ISSUE TITLE
Dashboard > Tetapan Masjid : On page load, tambah spinner

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#61]
Seperti gambarajah di bawah:

<img width="587" alt="Screenshot 2024-01-12 at 1 39 07 AM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/cb4c04c8-efed-4315-a6d7-15f0577d79fc">

**Comment by lurhays** [comment]
Dah siap. Pull request #67.
