### ISSUE TITLE
UI improvement in Dashboard>Khairat > Daftar

### ISSUE THREAD

**Issue by pojicode** [Dev4w4n/e-masjid.my#65]
Need to improve following UI

![image](https://github.com/Dev4w4n/e-masjid.my/assets/28385045/f24d5952-cd59-4a45-ab52-8fd11736c727)

**Comment by lurhays** [comment]
Macam ni ke?
- tag penandaan - jarak 5px
- improve button size and center - smaller button, display next to each other

<img width="677" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/186e8caf-c3bf-4843-aadb-4551d4307bca">
