### ISSUE TITLE
Khairat tag jadi pelik bila ada banyak tags

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#75]
Problem:
1. Bentuk tag jadi pelik (patut overflow ke next line) - CONTOH https://demo.e-masjid.my/ui#/khairat/daftar

<img width="1171" alt="Screenshot 2024-01-19 at 12 32 42 AM" src="https://github.com/Dev4w4n/e-masjid.my/assets/11247162/ce8fb5f1-2422-4e9a-a8cd-d89a6d6af5bc">

**Comment by lurhays** [comment]
Macam ni okay tak?
<img width="665" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/59ea6e0e-be88-400e-80c8-5ef9db2d07db">

**Comment by rohaizanr** [comment]
Ok dah. Terima kasih

**Comment by lurhays** [comment]
Pull request: #76
