### ISSUE TITLE
Download QR with Template (Peti Cadangan Online) 

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#81]
![WhatsApp Image 2024-01-18 at 4 28 02 PM](https://github.com/Dev4w4n/e-masjid.my/assets/11247162/ce2b5f69-6fcd-4869-b71b-d9fa18d40a85)

**Comment by lurhays** [comment]
Updated Muat Turun QR page.
<img width="683" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/4b07da36-055b-4ac0-b54a-fa01466585d6">

**Comment by rohaizanr** [comment]
Sila rujuk https://github.com/Dev4w4n/e-masjid.my/pull/112#issuecomment-1951382138

Terima kasih

**Comment by lurhays** [comment]
Updated:
<img width="719" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/ad575a3c-a9cd-4fd9-b9c1-1defe75e2454">

Sample download:
<img width="316" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/027218ec-766c-4e5b-9539-4c156188b001">

Merge komen dari PR #112 
<img width="639" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/ac9b2159-7abf-4878-93af-6843310e6c52">

**Comment by rohaizanr** [comment]
terima kasih
