### ISSUE TITLE
Carian Khairat pagination default

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/e-masjid.my#88]
Default page size 25 , 50 , 100, 200

**Comment by lurhays** [comment]
Updated default page size to 25, 50, 100, 200.
<img width="666" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/ac606390-5b20-413d-b834-e8c11f9c0c0d">

**Comment by lurhays** [comment]
Sori missed out. Pull Request #99 
<img width="853" alt="image" src="https://github.com/Dev4w4n/e-masjid.my/assets/5729687/c780804b-c1e8-43b8-937c-92aff7a36da7">

**Comment by rohaizanr** [comment]
terima kasih
